### ISSUE TITLE
Составление ТЗ и плана работ

### ISSUE THREAD

**Issue by evgeny-p** [ri57-sibsutis/gem-puzzle#1]
Примерное содержание ТЗ доступно в [статье](http://evgeny-p.github.io/teaching/materials/project/02-planning.html).

Definition of Done:
1. В [wiki](https://github.com/ri57-sibsutis/gem-puzzle/wiki) проекта написана статья с ТЗ.
2. В [issues](https://github.com/ri57-sibsutis/gem-puzzle/issues) созданы задачи.
3. ТЗ и план приняты заказчиком.

По готовности оставить комментарий в этой задаче.

**Comment by DashProk1407** [comment]
Посмотрите предварительное ТЗ, пожалуйста.

**Comment by evgeny-p** [comment]
Переходите к заведению задач.

Для первой итерации ТЗ хорошее, но если по мере заведения задач или выполнения работы потребуются уточнения, не стесняйтесь вносить правки.

Было бы неплохо отметить, как будут реализованы интерфейс и обработка пользовательского ввода. Можно вручную реализовать библиотеку для низкоуровневого взаимодействия с терминалом, можно использовать готовые решения (например, ncurses).

Указано, что таблица рекордов хранится в файле. Нужно задокументировать формат файла.

**Comment by DashProk1407** [comment]
Хорошо, исправим. Спасибо.
